Re-style mini-listing view, add style structure for full listing view.
jcsnorlax97/rentr pull request #153
Opened 2021-03-24 22:42 UTC by NathanCarriere

This re-styles the left panel small listing view so that the title fits in. This also adds some general structure for the right side panel. Currently there is no selection mechanism for changing which listing appears in the "full view". I will be expanding the QnA section next. 

Note the changes to the listing.css file... if they cause disruptions to stuff Mike is working on, or have unintended consequences I am unaware of, then I can reverse or undo those changes. 

![image](https://user-images.githubusercontent.com/51212155/112392946-4130d800-8cc8-11eb-95e3-05b685272732.png)

2021-03-24 22:53 UTC, jcsnorlax97 approved these changes
Skimming through quickly & looks fine to me.

2021-03-24 23:05 UTC, Mik3Qiao requested changes
Not sure why fetching listing is done in listingviewer, it should only display information for a single listing, it's index should be passed from its parent component (homePage)

2021-03-24 23:14 UTC, Mik3Qiao approved these changes

2021-03-25 03:20 UTC, AzizulHakim96 approved these changes

2021-03-25 04:18 UTC, RonnieDsouza reviewed
Merge conflict but otherwise looks good!

2021-03-25 19:27 UTC, merged